name: Geert-Jan GitHub Actions Demo

on:
  push:
    branches:
      - main   # only run when pushing to 'main'

jobs:
  create-mavne-package-skip-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Print funny line
      run: echo "Dit is een grappig zinnetje."

    - name: General checkout
      uses: actions/checkout@v5

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        cache-dependency-path: pom.xml  # watch your pom.xml

    - name: Build with Maven
      # run: mvn -B package -DskipTests --file pom.xml
      run: mvn -B package --file pom.xml